version: '3'

volumes:
  billboard-index:

networks:
  public:
    external: true

services:
  billboard-index:
    container_name: "billboard-index"
    image: joinnextblock/billboard-index:latest
    restart: unless-stopped
    volumes:
      - billboard-index:/app
    networks:
      - public