# Nostr Configuration
nostr:
  # Your private key in hex format (32-byte hex string)
  privateKey: "your_private_key_here"
  # List of relay URLs (must start with ws:// or wss://)
  relayUrls:
    - "wss://relay1.com"
    - "wss://relay2.net"

# Service Configuration
service:
  # Service information
  name: "Example Billboard"
  description: "Example Billboard description"
  # optional metadata
  picture: "https://image.nostr.build/5bf2e2eb3b858bf72c23e53ed1f41ed0f65b2c8a805eaa48dd506b7cfec4ab88.png"
  website: "https://github.com/gzuuus/dvmcp"
  kinds:
    - 1
    - 20
    - 21
    - 22
    - 1068