# Nostr Configuration
nostr:
  # Your private key in hex format (32-byte hex string)
  private_key: 'your_private_key_here'
  # List of relay URLs (must start with ws:// or wss://)
  relays:
    - 'wss://relay1.com'
    - 'wss://relay2.net'

# brokerage Configuration
brokerage:
  # brokerage information
  name: 'The PROMO PROTOCOL: Brokerage'
  description: 'The PROMO PROTOCOL: Brokerage'
  # optional metadata
  picture: 'https://image.nostr.build/5bf2e2eb3b858bf72c23e53ed1f41ed0f65b2c8a805eaa48dd506b7cfec4ab88.png'
  website: 'https://promo-protocol.org/brokerage'
  kinds:
    - 1
    - 20
    - 21
    - 22
    - 1068
