environment:
  log_level: "trace"

nostr:
  private_key: "2bee41196d3c931c28df64f27ae8f3c15fb535fb3aefe3ef0eeb55ba1cc93ee2"
  relays:
    - ws://localhost:10547

server:
  name: "PROMO Protocol Billboard"
  description: "PROMO Protocol Billboard"
  image: "https://promo-protocol.org/logo.png"
  url: "https://promo-protocol.org"
  kinds:
    - 22